para:
  train_dataset_length : 10000
  test_dataset_length : 250
  train_batch_size: 16000
  train_small_batch_size: 160
  test_batch_size: 10000
  full_iterations: 2000
  enc_train_iters: 50
  dec_train_iters: 500

  lr: 0.001
  seed: 1

  log_interval: 100
  epoch_szie : 200
  m: 7
  r: 3
  n: None
  k: None

  # Use in train validate data util
  snr: 6

  # Use in test_ber
  snr_list: 1,2,3,4,5,6
  Boosting_number_list: 1,2,3

  data_type: "7_3"
  logger_name: RM_{}_train
  CUDA_VISIBLE_DEVICES: "1"
  train_save_path_encoder: "./save/{}/rm_enc_{}_{}.pth"
  train_save_path_decoder: "./save/{}/rm_dec_{}_{}.pth"
  test_model_path: ./save/rm_{}/rm_{}_1.pth

data:
  rate: None   # dont edit, will init
  G : None # dont edit, will init
