para:
  train_dataset_length : 10
  test_dataset_length : 2
  train_batch_size: 10
  train_small_batch_size: 2
  test_batch_size: 10000
  full_iterations: 20
  enc_train_iters: 1
  dec_train_iters: 5

  lr: 0.001
  seed: 1

  log_interval: 100
  epoch_size : 200
  m: 2
  r: 1
  n: None
  k: None

  # Use in train validate data util
  snr: 6
 
  data_type: "2_1"
  logger_name: RM_{}_train
  CUDA_VISIBLE_DEVICES: "1"
  train_save_path_dir: "./save/{}/rm_{}"
  train_save_path_encoder: "./save/{}/rm_{}/enc_{}.pth"
  train_save_path_decoder: "./save/{}/rm_{}/dec_{}.pth"
  # test_model_path: ./save/rm_{}/rm_{}_1.pth

data:
  rate: None   # dont edit, will init
  G : None # dont edit, will init
test:
 # Use in test_ber
  snr_list: 1,2,3,4,5,6
  Boosting_number_list: 1,2,3
  snr: 6
  day: 29thSept 2021
  epoch_num: 10

  test_model_path_encoder: "./save/{}/rm_{}/enc_{}.pth"
  test_model_path_decoder: "./save/{}/rm_{}/dec_{}.pth"